# Generated by Django 3.0.4 on 2020-03-19 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('date_creation', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact', models.CharField(max_length=8)),
                ('status', models.BooleanField(default=True)),
                ('date_creation', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Educateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact', models.CharField(max_length=8)),
                ('date_de_naissance', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('date_creation', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact', models.CharField(max_length=8)),
                ('status', models.BooleanField(default=True)),
                ('date_creation', models.DateField(auto_now=True)),
                ('dren', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.Dren')),
            ],
        ),
        migrations.CreateModel(
            name='Localite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('date_creation', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('coefficient', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('date_creation', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('date_creation', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact', models.CharField(max_length=8)),
                ('date_de_naissance', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('date_creation', models.DateField(auto_now=True)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.Matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Sexe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('date_creation', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type_Ecole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('date_creation', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type_Enseignement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('date_creation', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type_Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('date_creation', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type_Statut_Ecole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('date_creation', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repartition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('date_creation', models.DateField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.Classe')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.Etablissement')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.Matiere')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.Professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Proviseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=8)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_de_naissance', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('date_creation', models.DateField(auto_now=True)),
                ('sexe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.Sexe')),
            ],
        ),
        migrations.CreateModel(
            name='Professeur_Etablissement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('date_creation', models.DateField(auto_now=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.Etablissement')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.Professeur')),
            ],
        ),
        migrations.AddField(
            model_name='professeur',
            name='sexe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.Sexe'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='type_matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.Type_Matiere'),
        ),
        migrations.CreateModel(
            name='Etablissement_Niveau_Educateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('date_creation', models.DateField(auto_now=True)),
                ('educateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.Educateur')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.Etablissement')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.Niveau')),
            ],
        ),
        migrations.AddField(
            model_name='etablissement',
            name='localite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.Localite'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='proviseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.Proviseur'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='type_ecole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.Type_Ecole'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='type_enseignement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.Type_Enseignement'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='type_statut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.Type_Statut_Ecole'),
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=8)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_de_naissance', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('date_creation', models.DateField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.Classe')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.Etablissement')),
                ('sexe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.Sexe')),
            ],
        ),
        migrations.AddField(
            model_name='educateur',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.Etablissement'),
        ),
        migrations.AddField(
            model_name='educateur',
            name='sexe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.Sexe'),
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.Niveau'),
        ),
        migrations.AddField(
            model_name='classe',
            name='professeur_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.Professeur'),
        ),
        migrations.AddField(
            model_name='classe',
            name='tablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.Etablissement'),
        ),
    ]
