# Generated by Django 3.0.4 on 2020-03-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educateur',
            name='matricule',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='matricule',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='matricule',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='proviseur',
            name='matricule',
            field=models.CharField(max_length=9),
        ),
    ]
