# Generated by Django 3.0.4 on 2020-03-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0002_auto_20200319_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='chef',
            field=models.BooleanField(default=False),
        ),
    ]
